export default {
    TRACK_A_LOAD_WITH_MOBILE_NUMBER: "Track a load with mobile number",
    CREATE_AN_ACCOUNT: "Create an account",
    CONTINUE_AS_A_GUEST: "Continue as a guest",
    OR: "OR",
    forceUpdateTitle: "RXO Drive needs an update",
    forceUpdateMessage: "A new version of RXO Drive is available. Update now?",
    forceUpdateBtn: "Update",
    SIGN: "Sign in",
    AVAILABLE_ORGANIZATIONS: "Available organizations",
    SELECT_CARRIER: "Select carrier",
    CARRIER: "Carrier",
    REQUIRED_INFORMATION: "Required Information",
    BRONZE: "BRONZE",
    SELECT_CARRIER_LABEL: "Select Carrier",
    CARRIER_PLACEHOLDER: "Click here to make a selection",
    recommendedloads_tab: "For You",
    mybids_tab: "Bids",
    myloads_tab: "My Loads",
    fuel_tab: "Fuel",
    findloads_tab: "Loads",
    more_tab: "More",
    RECOMMENDED_LOADS: "Recommended Loads For You",
    STOP: "Stop",
    RECOMMENDED_LOADS_LIST: "Recommended Loads List",
    OPEN_CO: "OPENCO",
    ACCEPTED_CO: "ACCEPTEDCO",
    REJECTED_CO: "REJECTEDCO",
    EXPIRED_CO: "EXPIREDCO",
    BID_REVIEW: "BIDREVIEW",
    BID_APPROVED: "BIDAPPROVED",
    BID_DECLINED: "BIDDECLINED",
    BID_EXPIRED: "BIDEXPIRED",
    OPEN_CO: "OPENCO",
    SOLD: "SOLD",
    Miles_Abb: "Miles",
    Mile_Abb: "MI",
    dot_unicode: "\u2022",
    distance: "Distance",
    deadhead: "Deadhead",
    deadhead_Abr: "DH",
    book_now: "Book Now",
    place_bid: "Place Bid",
    ALL_LOADS: "All Loads",
    DEDICATED_LANES: "Dedicated Lanes",
    ALL_EQUIPMENTS: "All Equipments",
    EQUIPMENT: "Equipment",
    ANYWHERE: "Anywhere",
    ANYTIME: "Anytime",
    SAVE_SEARCH: "Save Search",
    ORIGIN: "Origin",
    DESTINATION: "Destination",
    ONE_FIFTY: "150",
    VIEW_LOADS: "View Loads",
    LOAD_NUMBER: "Load Number",
    MILES: "Mi",
    PICK_UP: "Pick up",
    DELIVERY: "Delivery",
    ALL_EQUIPMENT: "All Equipment",
    EQUIPMENTTYPE: "Equipment Type",
    CLEAR: "Clear",
    SEARCH_CRITERIA: "Search Criteria",
    LBS: "LBS",
    MAX_WEIGHT: "Max Weight",
    EQUIPMENTCONDITION: "Equipment Condition",
    HOT_DEALS: "Hot Deals",
    PLACEHOLDER: "Select a date",
    HEADER: "Choose a date or range",
    END_DATE: "END_DATE",
    DONE: "Done",
    LOGOUT: "Logout",
    STATUS: "Status",
    SCORE: "Score",
    XPO_CARRIER_REWARDS_CAPPS: "DRIVE EXTRA",
    RXO_EXTRA_MARKETPLACE : "Extra Marketplace",
    HELP: "Help",
    CONTACT_SUPPORT: "Contact Support",
    POSTED_TRUCKS: "Posted Trucks",
    SAVED_SEARCHES: "Saved Searches",
    CERTIFICATION: "Certifications",
    CERTIFICATE_DES: "Get more loads. Make more money.",
    RXO_MARKET_DESC: "Get savings on fuel, maintenance and tires, retail, insurance and more!"
}